apiVersion: v1
kind: ServiceAccount
metadata:
  name: gtflp
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gtflp
rules:
  - apiGroups:
      - serving.knative.dev
      - metrics.k8s.io
      - extensions
      - apps
      - eventing.knative.dev
      - ""
    resources:
      - "pods/log"
      - "events"
      - "nodes"
      - "pods"
      - "deployments"
      - "replicasets"
    verbs:
      - get
      - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: gtflp
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: gtflp
subjects:
  - kind: ServiceAccount
    name: gtflp
    # UPDATE THIS TO MATCH YOUR NAMESPACE:
    namespace: demo
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: gtflp
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: "1"
    spec:
      serviceAccountName: gtflp
      containers:
        - image: gcr.io/fit-stream-305821/gtflp-74a7bfcfca304ccc24ab0c1018431452@sha256:0919a9eb957a218c95dfe5e511f31e98770293c620d654c094358a1a2b529b6f

---
