name: Deploy to KIND

on:
  push:
    # Sequence of patterns matched against refs/heads
    branches:    
      - main
    tags:        
      - v1.*      
jobs:
  create-cluster:
    runs-on: ubuntu-latest
    env:
      KO_DOCKER_REPO: docker.io/jeffthenaef
    steps:          
      - name: checkout
        uses: actions/checkout@v2

      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1.2.0
        
      - name: Run kubectl create ns demo
        run: kubectl create ns demo
        
      - name: Git clone kn plugin
        run: git clone https://github.com/JeffNeff/knative-tutorial.git
    
      - name: ./install-serving
        run:  ./knative-tutorial/setup/install-serving
        
      - name: ./install-eventing
        run:  ./knative-tutorial/setup/install-eventing
        
      - name: kubectl label ns demo eventing.knative.dev/injection=enabled
        run:  kubectl label ns demo eventing.knative.dev/injection=enabled

      - name: docker login -u jeffthenaef -p ${{ secrets.DOCKERHUB_PASSWORD }}
        run: docker login -u jeffthenaef -p ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: apply release manifest
        run: kubectl -n demo apply -f release.yaml

      - name: Sleep for 30 seconds
        run: sleep 60s
        shell: bash

      - name:  kubectl -n demo get ksvc
        run: kubectl -n demo get ksvc

      - name:  kubectl -n demo get pods
        run: kubectl -n demo get pods


